language: php

env:
    global:
    - setup=stable

matrix:
    fast_finish: true
    include:
    - php: 5.5
    - php: 5.5
      env: setup=lowest
    - php: 5.6
    - php: 5.6
      env: setup=lowest
    - php: 7.0
    - php: 7.0
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true
    - phpenv config-add curl.ini || true
    - phpenv config-add json.ini || true
    - travis_retry composer self-update

install:
    - if [[ $setup = 'stable' ]]; then travis_retry composer update --dev --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
    - if [[ $setup = 'lowest' ]]; then travis_retry composer update --dev --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: composer run test
